source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '10.0'

target 'AutoCompleteTextField_Example' do
  pod 'AutoCompleteTextField', :path => '../'
end

target 'AutoCompleteTextField_Tests' do
  pod 'AutoCompleteTextField', :path => '../'

  
end
